### ISSUE TITLE
Prepare release for Dataverse

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/LaroplanOCR#9]
The goal of this issue is to prepare a release for posting to the Harvard Dataverse.

We'd like to structure this in such a way to keep maintenance costs low going forward, i.e. so that a new release in github can be easily pushed as an update to Dataverse.

Once we have a plan ready I think we can:
- [x] Post a release in github
- [x] Upload to the Dataverse
- [x] Take the repository public

**Comment by santiagohermo** [comment]
Summary: In this issue we prepared code to build a release for the Dataverse. After that, we 

1. Added a [first release](https://github.com/JMSLab/LaroplanOCR/releases/tag/v1.0.0) to the repo
2. Added the data to the Harvard Dataverse: https://github.com/JMSLab/LaroplanOCR/releases/tag/v1.0.0
3. Set the repository to public

Changes merged to `main` in https://github.com/JMSLab/LaroplanOCR/commit/a2c1884065bb96fc17444d6c34f183fa9a3ac702.
